version: '3.4'

networks:
  demoblazorapp:

services:
  demoappdb:
    container_name: app-db
    image: 853192360440.dkr.ecr.us-west-2.amazonaws.com/db:latest
    #image: mcr.microsoft.com/mssql/server:2019-latest
    build:
      context: .
      dockerfile: DemoBlazorServerApp/database-demo/Dockerfile
    ports:
      - 8002:1433
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=password@12345#
    networks:
      - demoblazorapp
  demoblazorserverapp:
    container_name: demo-blazor-app
    image: 853192360440.dkr.ecr.us-west-2.amazonaws.com/app:latest
    build:
      context: .
      dockerfile: DemoBlazorServerApp/Dockerfile
    ports:
      - 8001:80
    depends_on:
      - demoappdb
    environment:
      - DB_HOST=demoappdb
      - DB_NAME=DemoBlazorApp
      - DB_SA_PASSWORD=password@12345#
    networks:
      - demoblazorapp
